---
- name: Install NTP daemon.
  apt:
    name: ntp
    state: present
    update_cache: yes

- name: Start and enable NTP daemon.
  service:
    name: ntp
    state: started
    enabled: yes

- name: Synchronize time via NTP daily.
  cron:
    name: Synchronize time via NTP.
    minute: "0"
    hour: "0"
    user: root
    job: ntpd 0.pool.ntp.org 1.pool.ntp.org 2.pool.ntp.org 3.pool.ntp.org