---
- name: Install nginx.
  apt:
    name: nginx
    state: latest
    update_cache: yes

- name: Add custom 'kibana.conf' configuration.
  copy:
    src: kibana.conf
    dest: /etc/nginx/conf.d/kibana.conf
  notify:
    - Restart nginx

- name: Remove default web server configuration.
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

