---
- name: Install nginx.
  apt:
    name: nginx
    state: latest
    update_cache: yes

- name: Create 'kibana-reverse-proxy.cfg' using custom template.
  template:
    src: kibana-reverse-proxy.j2
    dest: /etc/nginx/sites-available/kibana-reverse-proxy.cfg

- name: Link enabled configuration to 'kibana-reverse-proxy.cfg'.
  file:
    src: /etc/nginx/sites-available/kibana-reverse-proxy.cfg
    dest: /etc/nginx/sites-enabled/default
    state: link
  notify:
    - Restart nginx