---
- name: Install nginx.
  apt:
    name: nginx
    state: latest
    update_cache: yes

#- name: Create 'nginx.conf' using custom template to enable upstream proxy forwarding.
#  template:
#    src: nginx.j2
#    dest: /etc/nginx/nginx.conf

#- name: Add custom 'kibana-reverse-proxy.cfg' configuration.
#  copy:
#    src: kibana-reverse-proxy.cfg
#    dest: /etc/nginx/sites-available/kibana-reverse-proxy.cfg

- name: Add custom 'kibana.conf' configuration.
  copy:
    src: kibana.conf
    dest: /etc/nginx/conf.d/kibana.conf
  notify:
    - Restart nginx

#- name: Link enabled configuration to 'kibana-reverse-proxy.cfg'.
#  file:
#    src: /etc/nginx/sites-available/kibana-reverse-proxy.cfg
#    dest: /etc/nginx/sites-enabled/default
#    state: link

##TODO: remove default nginx config