---
- name: Install software-properties-common to enable ppa and avoid recommended packages.
  apt:
    name: software-properties-common
    state: latest
    install_recommends: no

- name: Add repo 'ppa:vbernat/haproxy-2.8'
  apt_repository:
    repo: ppa:vbernat/haproxy-2.8

- name: Install haproxy.
  apt:
    name: haproxy
    update_cache: yes

- name: Edit haproxy configuration file to enable 'roundrobin' LB strategy.
  blockinfile:
    path: /etc/haproxy/haproxy.cfg
    block: |
      frontend http_front
              bind *:80
              stats uri /haproxy?stats
              default_backend http_back

      backend http_back
              balance roundrobin

- name: Add backend hosts.
  lineinfile:
    path: /etc/haproxy/haproxy.cfg
    insertafter: 'balance roundrobin'
    line: "        server {{ item.name }} {{ item.ip }}:{{ item.port }} check"
  loop: "{{ backend }}"
  notify:
    - Restart haproxy

