---
- name: Install software-properties-common to enable ppa and avoid recommended packages.
  apt:
    name: software-properties-common
    state: latest
    install_recommends: no

- name: Add repo 'ppa:adiscon/v8-stable'.
  apt_repository:
    repo: ppa:adiscon/v8-stable

- name: Install rsyslog.
  apt:
    name: rsyslog
    state: present
    update_cache: yes

- name: Add custom 'rsyslog.conf' file.
  copy:
    src: rsyslog.conf
    dest: /etc/rsyslog.conf

- name: Add custom '50-default.conf' file.
  copy:
    src: 50-default.conf
    dest: /etc/rsyslog.d/50-default.conf

- name: Add custom 'elk.conf' file.
  copy:
    src: elk.conf
    dest: /etc/rsyslog.d/elk.conf

- name: Create 'localsyslog.conf' using custom template.
  template:
    src: localsyslog.j2
    dest: /etc/rsyslog.d/localsyslog.conf
  notify:
    - Restart rsyslog
