---
- name: Common setup.
  hosts: all
  become: true
  roles:
#    - apt
#    - ntp
#    - monit

#- name: Haproxy LB setup.
#  hosts: haproxy
#  become: true
#  vars:
#    backend:
#      - { name: webui, ip: 192.168.4.6, port: 80}
#
#  roles:
#    - haproxy

#- name: Logstash log collecting server setup.
#  hosts: logstash
#  become: true
#  vars:
#    elasticsearch_jvm_xms:
#      - 256m
#    elasticsearch_jvm_xmx:
#      - 256m
#  roles:
#    - java
#    - logstash
#    - elasticsearch

- name: Kibana visualization server setup.
  hosts: webui
  become: true
  roles:
    - rsyslog
    #- kibana




