---
- name: Common setup.
  hosts: all
  become: true
  roles:
    - apt
    - ntp
    - monit

- name: Haproxy LB setup.
  hosts: haproxy
  become: true
  vars:
    backend:
#TODO: add aws pucblic ip of webui
      - { name: webui, ip: 192.168.4.6, port: 80}

  roles:
    - haproxy

  post_tasks:
    - name: Add 'haproxy_instance.ini' file.
      copy:
        dest: /etc/haproxy_instance.ini
        content: |
          [general]

    - name: Add VM UUID to 'haproxy_instance.ini' file.
      shell: echo "uniqueID="$(dmidecode -s system-uuid) >> /etc/haproxy_instance.ini

- name: Logstash log collecting server setup.
  hosts: logstash
  become: true
  vars:
    elasticsearch_jvm_xms:
      - 256m
    elasticsearch_jvm_xmx:
      - 256m
  roles:
    - java
    - logstash
    - elasticsearch

  post_tasks:
    - name: Add 'logstash_instance.ini' file.
      copy:
        dest: /etc/logstash_instance.ini
        content: |
          [general]

    - name: Add VM UUID to 'logstash_instance.ini' file.
      shell: echo "uniqueID="$(dmidecode -s system-uuid) >> /etc/logstash_instance.ini

- name: Kibana visualization server setup.
  hosts: webui
  become: true
  vars:
    logstash_ip:
#TODO: add aws pucblic ip of logstash
      - 192
  roles:
    - rsyslog
    - kibana
    - nginx

  post_tasks:
    - name: Add 'webui_instance.ini' file.
      copy:
        dest: /etc/webui_instance.ini
        content: |
          [general]

    - name: Add VM UUID to 'webui_instance.ini' file.
      shell: echo "uniqueID="$(dmidecode -s system-uuid) >> /etc/webui_instance.ini




