---
- name: Common setup.
  hosts: elk
  become: true
  roles:
    - apt
    - ntp
    - monit

- name: Haproxy LB setup.
  hosts: haproxy
  become: true
  vars:
    backend:
      - { name: webui, ip: 192.168.4.6, port: 80}

  roles:
    - haproxy

#- name: Logstash log server setup.
#  hosts: logstash



