---
- name: Common setup.
  hosts: all
  become: true
  vars:
    email_username:
    email_password:
  roles:
    - apt
    - ntp
    - monit

- name: Haproxy LB setup.
  hosts: haproxy
  become: true
  vars:
    backend_name: webui
    backend_ip: 16.170.173.149
  roles:
    - haproxy

  post_tasks:
    - name: Add 'haproxy_instance.ini' file.
      copy:
        dest: /etc/haproxy_instance.ini
        content: |
          [general]

    - name: Add VM UUID to 'haproxy_instance.ini' file.
      shell: echo "uniqueID="$(dmidecode -s system-uuid) >> /etc/haproxy_instance.ini

- name: Logstash log collecting server setup.
  hosts: logstash
  become: true
  vars:
    elasticsearch_jvm_xms: 256m
    elasticsearch_jvm_xmx: 256m
    logstash_ip: 51.20.55.6
  roles:
    - java
    - logstash
    - elasticsearch

  post_tasks:
    - name: Add 'logstash_instance.ini' file.
      copy:
        dest: /etc/logstash_instance.ini
        content: |
          [general]

    - name: Add VM UUID to 'logstash_instance.ini' file.
      shell: echo "uniqueID="$(dmidecode -s system-uuid) >> /etc/logstash_instance.ini

- name: Kibana visualization server setup.
  hosts: webui
  become: true
  vars:
    elasticsearch_logstash_ip: 51.20.55.6
    kibana_ip: 16.170.173.149
  roles:
    - rsyslog
    - kibana
    - nginx

  post_tasks:
    - name: Add 'webui_instance.ini' file.
      copy:
        dest: /etc/webui_instance.ini
        content: |
          [general]

    - name: Add VM UUID to 'webui_instance.ini' file.
      shell: echo "uniqueID="$(dmidecode -s system-uuid) >> /etc/webui_instance.ini




