---
- name: Install monit
  apt:
    name: monit
    state: present

- name: Create 'monitrc' using custom template.
  template:
    src: monitrc.j2
    dest: /etc/monit/monitrc
  notify:
    - Restart monit





