---
- name: Restart elasticsearch
  service:
    name: elasticsearch
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: Restart logstash
  service:
    name: logstash
    state: restarted
    daemon_reload: yes
    enabled: yes