---
- name: Install dependencies.
  apt:
    name:
      - apt-transport-https
      - openssl
      - wget
    state: latest
    update_cache: yes

- name: Import ES GPG key.
  shell: |
    wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -

- name: Add kibana repo to apt.
  apt_repository:
    repo: deb  https://artifacts.elastic.co/packages/8.x/apt  stable main
    state: present
    filename: kibana-8.x.list

- name: Update apt cache and install kibana.
  apt:
    name: kibana
    state: present
    update_cache: yes

- name: Update the '/etc/hosts' file with host name.
  lineinfile:
    dest: "/etc/hosts"
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_host }} {{item}}"
    state: present
  when: hostvars[item].ansible_host is defined
  with_items: "{{groups['elk']}}"

- name: Add Instance Private IP to '/etc/hosts'
  shell: |
    echo "ec2private " >> /etc/hosts
    

- name: Create custom 'kibana.yml' with provided password for 'kibana_system'.
  template:
    src: kibana.j2
    dest: /etc/kibana/kibana.yml
  notify:
    - Restart kibana