---
- name: Install dependencies.
  apt:
    name:
      - apt-transport-https
      - openssl
      - wget
    state: latest
    update_cache: yes

- name: Import ES GPG key.
  shell: |
    wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -

- name: Add kibana repo to apt.
  apt_repository:
    repo: deb  https://artifacts.elastic.co/packages/8.x/apt  stable main
    state: present
    filename: kibana-8.x.list

- name: Update apt cache and install kibana.
  apt:
    name: kibana
    state: present
    update_cache: yes

- name: Update the '/etc/hosts' file with Public IP addresses of [elk] group.
  lineinfile:
    dest: "/etc/hosts"
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_host }} {{item}}"
    state: present
  when: hostvars[item].ansible_host is defined
  with_items: "{{groups['elk']}}"

- name: Add Instance Private IP to '/etc/hosts'
  shell: |
    echo -n $(TOKEN=`curl -X PUT "http://169.254.169.254/latest/api/token" \
    -H "X-aws-ec2-metadata-token-ttl-seconds: 21600" 2>/dev/null ` &&
    curl -H "X-aws-ec2-metadata-token: $TOKEN" \
    http://169.254.169.254/latest/meta-data/local-ipv4 2>/dev/null) >> /etc/hosts &&
    echo " ec2private" >> /etc/hosts

- name: Add custom 'kibana.yml'.
  copy:
    src: kibana.yml
    dest: /etc/kibana/kibana.yml


#TODO: get password for kibana_system from vault (env KIBANA_PASSWORD)

- name: Create string with password for 'kibana_system'.
  shell: |
    export KIBANA_PASSWORD_STRING="elasticsearch.password: \"${KIBANA_PASSWORD}\""

- name: Write string with password to 'kibana.yml'.
  shell: |
    sed -i "46i$KIBANA_PASSWORD_STRING" /etc/kibana/kibana.yml
  notify:
    - Restart kibana