---
- name: Install dependencies.
  apt:
    name:
      - apt-transport-https
      - openssl
      - wget
    state: latest
    update_cache: yes

- name: Import ES GPG key.
  shell: |
    wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -

- name: Add kibana repo to apt.
  apt_repository:
    repo: deb  https://artifacts.elastic.co/packages/8.x/apt  stable main
    state: present
    filename: kibana-8.x.list

- name: Update apt cache and install kibana.
  apt:
    name: kibana
    state: present
    update_cache: yes

- name: Create custom 'kibana.yml' with elasticsearch ip.
  template:
    src: kibana.j2
    dest: /etc/rsyslog.d/localsyslog.conf
  notify:
    - Restart kibana