---
- name: Install elasticsearch.
  apt:
    name: elasticsearch
    state: present
    update_cache: yes
  notify:
    - Restart elasticsearch

- name: Add custom 'elasticsearch.yml' file.
  copy:
    src: files/elasticsearch.yml
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch

- name: Set 'elasticsearch' user to be owner of 'elasticsearch' dir.
  file:
    path: /usr/share/elasticsearch
    state: directory
    recurse: yes
    owner: elasticsearch
    group: elasticsearch

- name: Set min JVM heap size.
  lineinfile:
    dest: /etc/elasticsearch/jvm.options
    regexp: "^-Xms"
    line: "-Xms{{ elasticsearch_jvm_xms }}"
- name: Set max JVM heap size.
  lineinfile:
    dest: /etc/elasticsearch/jvm.options
    regexp: "^-Xmx"
    line: "-Xmx{{ elasticsearch_jvm_xmx }}"
  notify:
    - Restart elasticsearch

- name: Add 'logstash_instance.ini' file.
  copy:
    dest: /etc/logstash_instance.ini
    content: |
      [general]

- name: Add VM UUID to 'logstash_instance.ini' file.
  shell: echo "uniqueID="$(dmidecode -s system-uuid) >> /etc/logstash_instance.ini