---
- name: Install elasticsearch.
  apt:
    name: elasticsearch
    state: present
    update_cache: yes
  notify:
    - Restart elasticsearch

- name: Add custom 'elasticsearch.yml' file.
  copy:
    src: elasticsearch.yml
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch

- name: Set 'elasticsearch' linux user to be owner of 'elasticsearch' dir.
  file:
    path: /usr/share/elasticsearch
    state: directory
    recurse: yes
    owner: elasticsearch
    group: elasticsearch

- name: Set min JVM heap size for elasticsearch.
  lineinfile:
    dest: /etc/elasticsearch/jvm.options
    regexp: "^-Xms"
    line: "-Xms{{ elasticsearch_jvm_xms }}"

- name: Set max JVM heap size for elasticsearch.
  lineinfile:
    dest: /etc/elasticsearch/jvm.options
    regexp: "^-Xmx"
    line: "-Xmx{{ elasticsearch_jvm_xmx }}"

- name: Create custom elasticsearch cluster superuser.
  shell: |
    /usr/share/elasticsearch/bin/elasticsearch-users \
    useradd $ELK_ADMIN_USERNAME -p $ELK_ADMIN_PASSWORD -r superuser
  environment:
    ELK_ADMIN_USERNAME: "{{ elk_admin_username }}"
    ELK_ADMIN_PASSWORD: "{{ elk_admin_password }}"

################################################################################
# Note: Elasticsearch can not create user with auto-generated password.
#       Only able to replace old password with new auto-generated password.
################################################################################

- name: Create elasticsearch cluster superuser for logstash.
  shell: |
    /usr/share/elasticsearch/bin/elasticsearch-users useradd logstash_internal \
    -p temporaryPassword -r superuser

- name: Set new auto-generated password for 'logstash_internal' user and write it into config.
  shell: |
    LOGSTASH_PASSWORD=$(echo "y" |
    /usr/share/elasticsearch/bin/elasticsearch-reset-password \
    -u logstash_internal -a -s 2>/dev/null) 
    LOGSTASH_PASSWORD_STRING="password => \"${LOGSTASH_PASSWORD}\"" &&
    sed -i "4i\\\t${LOGSTASH_PASSWORD_STRING}" /etc/logstash/conf.d/output.conf
  notify:
    - Restart elasticsearch
    - Restart logstash

################################################################################
# Note: Elasticsearch does not show existing user's password.
#       Only able to reset it.
################################################################################

- name: Set new auto-generated password for 'kibana_system' and put into Vault.
  shell: |
    vault write kv/kibana_password value=$(echo "y" |
    /usr/share/elasticsearch/bin/elasticsearch-reset-password \
    -u kibana_system -a -s 2>/dev/null)
  environment:
    VAULT_ADDR: "{{ vault_addr }}"
    VAULT_TOKEN: "{{ vault_token }}"
    

